### ISSUE TITLE
Repo outdated?

### ISSUE THREAD

**Issue by chillu** [silverstripe-archive/documentation-examples#2]
@wilr I don't think SilverStripe Ltd. can commit to maintaining the docs examples here. Last commit was two years ago, so they'll already be missing examples, with others outdated. 

The approach has been (partially) superseded by Aaron's https://github.com/silverstripe/one-ring-rentals repo, which contains the new "lessons" code. It might suffer the same fate eventually, of course ;)

So, do you either want to take the repo into your own Github domain, or start a discussion on the mailinglist on how we can efficiently keep the docs examples up to date with docs? If neither of them is an option, we'll remove the repo in two weeks time.

Background: https://groups.google.com/forum/#!topic/silverstripe-dev/vgQZpUnxrI4

**Comment by wilr** [comment]
I think it's worth keeping all the documentation code examples runnable. Perhaps move these to be as part of docs.ss project?

**Comment by chillu** [comment]
I think unless they're in the same repo as the documentation itself (core), they're bound to get outdated. And pulling them into core will require some hacks around only making the PHP executable with certain flags set. I like the "runnable docs" approach in theory, but has anybody used this repo in the last couple of years to verify a new release, check that docs don't have syntax errors, etc?

/cc @tractorcow @camfindlay

**Comment by camfindlay** [comment]
Are these for the older "tutorials" that were listed on the docs site? These might going forward have been superseded by the online lessons we have (which includes a working project repo for the one ring rentals site).

**Comment by wilr** [comment]
@camfindlay more for the 'in page' snippets and how-tos.

**Comment by chillu** [comment]
I'm moving this repo over to `silverstripe-labs` in preparation for relabeling the org to `silverstripe-archive`
